### ISSUE TITLE
IPython.display.Markdown - `_repr_*_()`

### ISSUE THREAD

**Issue by eliasmistler** [ideonate/nb2xls#4]
Found another one 🐞 

```python
from IPython.display import Markdown, display

display(Markdown('''
# Hi Dan
1. Thanks for fixing the last issue so quickly
1. This library is really cool
1. I'll probably start using it for work soon
'''))
```

results in:
```
<IPython.core.display.Markdown object>
```

The same issue occurs without the `display`. Similarly, `IPython.display.HTML` and `Latex` fail. I suspect you might need an explicit resolution of `_repr_*_()` functions, as it's done in `IPython` itself:  [IPython docs](https://ipython.readthedocs.io/en/stable/config/integrating.html#rich-display) and the [corresponding code](https://github.com/ipython/ipython/blob/master/IPython/core/display.py) (check the `display` function)

*Note*: Somewhat surprisingly (to me, anyway), the following contrived example of a custom object displayed correctly:
```python
from random import choice
from string import ascii_lowercase

def _random_str(length: int):
    return ''.join(choice(ascii_lowercase) for _ in range(length))

class RandomUser:
    def __init__(self):
        self.user = _random_str(10)
        self.password = _random_str(20)
        
    def _repr_html_(self):
        return f'''
        <table>
        <tr><th>User: </th><td>{self.user}</td>
        <tr><th>Password: </th><td>{self.password}</td>
        </table>
        '''
    
RandomUser()
```

On the other hand, this code:

```python
import json

class DisplayDict(dict):
    def _repr_json_(self):
        return self
    
DisplayDict({'hello': 'world'})
```

results in another error:
```
nbconvert failed: split
```

**Comment by danlester** [comment]
Thanks again! I have added support for text/markdown to the list of supported mimetypes explicitly allowed in a code cell (previously, markdown was only expected in a markdown cell).

Note that there is necessarily a hierarchy of mimetypes to display where multiple are available. For example, it chooses text/html over text/plain should both be available.

text/html was already supported which is why your second example was fine.

application/json was supposedly supported before but just processed in the same way as text/plain - but in fact the data was a node object of nbformat and there wasn't a test ipynb that attempted to use this. So now it just does a repr of the node as you suggested. (Clearly a structured display of json data would be possible, indented and split across cells etc. If useful, I will be happy to try this.)

In general, it's great to have more test ipynb files and this is the best way to advance the project! So feel free even to send interesting ipynb files that work well for you so they can be added to the test suite.

At some point, if there are many examples, we may need to make more difficult decisions on how to interpret the notebooks - e.g. in some cases different mimetypes will be better for different cases.

Version 0.1.4 is now released containing these changes.
